---
- hosts: all
  gather_facts: yes

  tasks:
 
  - name: This is linux
    debug: msg=“Linux“
    when: ansible_system == "Linux"

  - name: This is windows
    debug: msg=“Windows“
    when: ansible_system == "Win32NT"

  - name: Create a directory if it does not exist
    file:
      path: /etc/some_directory
      state: directory
      mode: '0755'
    when: ansible_system == "Linux"
