---
- name: Create scheduled task to copy files
  hosts: all
  vars:
    task_name: Copy archived logs to server  # Replace with the desired task name
    task_trigger_frequency: daily  # Replace with the desired trigger frequency (e.g., daily, weekly, monthly)
    task_trigger_time: '23:00'  # Replace with the desired trigger time in 24-hour format (e.g., '06:00')
    location_ps1: "C:\\ArchiveFile.ps1"
    location_pwd: "C:\\Credential.enc"
    location_src: "C:\\Temp\\Copy demo\\Source"
    location_dest: "\\\\localhost\\
      
  tasks:
  
  - name: Creates encryped file of service acount password used to connect to file storage 
    win_shell: | "
      # Convert text to secure string
      $securePassword = ConvertTo-SecureString {{ storage_password }} -AsPlainText -Force
        
      # Save the secure password to a text file
      $securePassword | ConvertFrom-SecureString | Out-File -FilePath {{ location_pwd }}"
    become: true
    become_user: "{{ service_username }}"
    become_password: "{{ service_password }}"
    no_log: true
