---
- name: Create scheduled task to copy files
  hosts: all
  gather_facts: false
  vars:
    task_name: "Copy archived logs to server"  # Replace with the desired task name
    task_trigger_frequency: "daily"  # Replace with the desired trigger frequency (e.g., daily, weekly, monthly)
    task_trigger_time: "23:00"  # Replace with the desired trigger time in 24-hour format (e.g., '06:00')
    location_ps1: "C:\\Temp\\ArchiveFile.ps1"
    location_pwd: "C:\\Temp\\Credential.enc"
    location_src: "C:\\Temp\\Copy demo\\Source"
    location_dest: "\\\\localhost\\"
      
  tasks:

    - name: Copy file from playbook
      win_copy:
        src: CreatedEncryptedFile.ps1
        dest: c:\Temp\CreatedEncryptedFile.ps1

    - name: Run command
      win_shell: |
        '$Username   = "training"
        $Password   = ConvertTo-SecureString -String "Training1!" -AsPlainText -Force
        $Credential = New-Object -Type PSCredential($Username,$Password)
        Invoke-Command -ComputerName localhost -Credential $Credential -ScriptBlock {
            c:\Temp\CreatedEncryptedFile.ps1 -Password {{ storage_password }} -SaveLocation {{ location_pwd }}
        }'
